/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type BedId = bigint;
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BloodStock {
    hospitalId: HospitalId;
    bloodGroup: BloodGroup;
    quantity: bigint;
    minQuantity: bigint;
}
export interface Bed {
    id: BedId;
    status: BedStatus;
    bedType: BedType;
    hospitalId: HospitalId;
}
export type MedicineId = bigint;
export type SupplierId = bigint;
export interface Medicine {
    id: MedicineId;
    expiryDate: Time;
    name: string;
    hospitalId: HospitalId;
    quantity: bigint;
    minQuantity: bigint;
    supplierId?: SupplierId;
}
export interface Supplier {
    id: SupplierId;
    contactInfo: string;
    name: string;
    hospitalId: HospitalId;
}
export interface UserProfile {
    appRole: AppRole;
    name: string;
    hospitalId?: HospitalId;
}
export type HospitalId = string;
export enum AppRole {
    patient = "patient",
    doctor = "doctor",
    superAdmin = "superAdmin",
    hospitalAdmin = "hospitalAdmin"
}
export enum BedStatus {
    occupied = "occupied",
    available = "available"
}
export enum BedType {
    ICU = "ICU",
    general = "general"
}
export enum BloodGroup {
    Aneg = "Aneg",
    Apos = "Apos",
    Bneg = "Bneg",
    Bpos = "Bpos",
    Oneg = "Oneg",
    Opos = "Opos",
    ABneg = "ABneg",
    ABpos = "ABpos"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBed(hospitalId: HospitalId, bedType: BedType): Promise<BedId>;
    addMedicine(hospitalId: HospitalId, name: string, quantity: bigint, minQuantity: bigint, expiryDate: Time, supplierId: SupplierId | null): Promise<void>;
    addSupplier(hospitalId: HospitalId, name: string, contactInfo: string): Promise<SupplierId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignUserProfile(user: Principal, profile: UserProfile): Promise<void>;
    deleteMedicine(id: MedicineId): Promise<void>;
    getAllBloodStock(hospitalId: HospitalId): Promise<Array<BloodStock>>;
    getAllMedicines(hospitalId: HospitalId): Promise<Array<Medicine>>;
    getAllSuppliers(hospitalId: HospitalId): Promise<Array<Supplier>>;
    getBed(id: BedId): Promise<Bed | null>;
    getBedStats(hospitalId: HospitalId): Promise<{
        total: bigint;
        occupied: bigint;
        available: bigint;
        icuOccupied: bigint;
        icuAvailable: bigint;
    }>;
    getBedStatsLegacy(hospitalId: HospitalId): Promise<{
        icuBeds: bigint;
        occupiedBeds: bigint;
        totalBeds: bigint;
        availableBeds: bigint;
    }>;
    getBedsByStatus(hospitalId: HospitalId, status: BedStatus): Promise<Array<Bed>>;
    getBedsByTypeAndStatus(hospitalId: HospitalId, bedType: BedType, status: BedStatus): Promise<Array<Bed>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExpiringMedicines(hospitalId: HospitalId): Promise<Array<Medicine>>;
    getLowStockBloodGroups(hospitalId: HospitalId): Promise<Array<BloodGroup>>;
    getLowStockMedicines(hospitalId: HospitalId): Promise<Array<Medicine>>;
    getMedicinesBySupplier(supplierId: SupplierId): Promise<Array<Medicine>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBedStatus(id: BedId, status: BedStatus): Promise<void>;
    updateBloodStock(hospitalId: HospitalId, bloodGroup: BloodGroup, quantity: bigint, minQuantity: bigint): Promise<void>;
    updateMedicine(id: MedicineId, quantity: bigint | null, minQuantity: bigint | null, expiryDate: Time | null, supplierId: SupplierId | null): Promise<void>;
    updateSupplier(id: SupplierId, contactInfo: string): Promise<void>;
}
import type { AppRole as _AppRole, Bed as _Bed, BedId as _BedId, BedStatus as _BedStatus, BedType as _BedType, BloodGroup as _BloodGroup, BloodStock as _BloodStock, HospitalId as _HospitalId, Medicine as _Medicine, MedicineId as _MedicineId, SupplierId as _SupplierId, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBed(arg0: HospitalId, arg1: BedType): Promise<BedId> {
        if (this.processError) {
            try {
                const result = await this.actor.addBed(arg0, to_candid_BedType_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBed(arg0, to_candid_BedType_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addMedicine(arg0: HospitalId, arg1: string, arg2: bigint, arg3: bigint, arg4: Time, arg5: SupplierId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicine(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicine(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addSupplier(arg0: HospitalId, arg1: string, arg2: string): Promise<SupplierId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupplier(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupplier(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignUserProfile(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignUserProfile(arg0, to_candid_UserProfile_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignUserProfile(arg0, to_candid_UserProfile_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteMedicine(arg0: MedicineId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedicine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedicine(arg0);
            return result;
        }
    }
    async getAllBloodStock(arg0: HospitalId): Promise<Array<BloodStock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBloodStock(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBloodStock(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMedicines(arg0: HospitalId): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedicines(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedicines(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSuppliers(arg0: HospitalId): Promise<Array<Supplier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSuppliers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSuppliers(arg0);
            return result;
        }
    }
    async getBed(arg0: BedId): Promise<Bed | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBed(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBed(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBedStats(arg0: HospitalId): Promise<{
        total: bigint;
        occupied: bigint;
        available: bigint;
        icuOccupied: bigint;
        icuAvailable: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBedStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBedStats(arg0);
            return result;
        }
    }
    async getBedStatsLegacy(arg0: HospitalId): Promise<{
        icuBeds: bigint;
        occupiedBeds: bigint;
        totalBeds: bigint;
        availableBeds: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getBedStatsLegacy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBedStatsLegacy(arg0);
            return result;
        }
    }
    async getBedsByStatus(arg0: HospitalId, arg1: BedStatus): Promise<Array<Bed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBedsByStatus(arg0, to_candid_BedStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBedsByStatus(arg0, to_candid_BedStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBedsByTypeAndStatus(arg0: HospitalId, arg1: BedType, arg2: BedStatus): Promise<Array<Bed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBedsByTypeAndStatus(arg0, to_candid_BedType_n8(this._uploadFile, this._downloadFile, arg1), to_candid_BedStatus_n33(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBedsByTypeAndStatus(arg0, to_candid_BedType_n8(this._uploadFile, this._downloadFile, arg1), to_candid_BedStatus_n33(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpiringMedicines(arg0: HospitalId): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpiringMedicines(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpiringMedicines(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockBloodGroups(arg0: HospitalId): Promise<Array<BloodGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockBloodGroups(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockBloodGroups(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockMedicines(arg0: HospitalId): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockMedicines(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockMedicines(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedicinesBySupplier(arg0: SupplierId): Promise<Array<Medicine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicinesBySupplier(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicinesBySupplier(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBedStatus(arg0: BedId, arg1: BedStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBedStatus(arg0, to_candid_BedStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBedStatus(arg0, to_candid_BedStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBloodStock(arg0: HospitalId, arg1: BloodGroup, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBloodStock(arg0, to_candid_BloodGroup_n45(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBloodStock(arg0, to_candid_BloodGroup_n45(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async updateMedicine(arg0: MedicineId, arg1: bigint | null, arg2: bigint | null, arg3: Time | null, arg4: SupplierId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedicine(arg0, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedicine(arg0, to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n47(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n48(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateSupplier(arg0: SupplierId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplier(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_BedStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BedStatus): BedStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_BedType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BedType): BedType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Bed_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bed): Bed {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_BloodGroup_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodGroup): BloodGroup {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_BloodStock_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodStock): BloodStock {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Medicine_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medicine): Medicine {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierId]): SupplierId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bed]): Bed | null {
    return value.length === 0 ? null : from_candid_Bed_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HospitalId]): HospitalId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hospitalId: _HospitalId;
    bloodGroup: _BloodGroup;
    quantity: bigint;
    minQuantity: bigint;
}): {
    hospitalId: HospitalId;
    bloodGroup: BloodGroup;
    quantity: bigint;
    minQuantity: bigint;
} {
    return {
        hospitalId: value.hospitalId,
        bloodGroup: from_candid_BloodGroup_n20(_uploadFile, _downloadFile, value.bloodGroup),
        quantity: value.quantity,
        minQuantity: value.minQuantity
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MedicineId;
    expiryDate: _Time;
    name: string;
    hospitalId: _HospitalId;
    quantity: bigint;
    minQuantity: bigint;
    supplierId: [] | [_SupplierId];
}): {
    id: MedicineId;
    expiryDate: Time;
    name: string;
    hospitalId: HospitalId;
    quantity: bigint;
    minQuantity: bigint;
    supplierId?: SupplierId;
} {
    return {
        id: value.id,
        expiryDate: value.expiryDate,
        name: value.name,
        hospitalId: value.hospitalId,
        quantity: value.quantity,
        minQuantity: value.minQuantity,
        supplierId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.supplierId))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BedId;
    status: _BedStatus;
    bedType: _BedType;
    hospitalId: _HospitalId;
}): {
    id: BedId;
    status: BedStatus;
    bedType: BedType;
    hospitalId: HospitalId;
} {
    return {
        id: value.id,
        status: from_candid_BedStatus_n29(_uploadFile, _downloadFile, value.status),
        bedType: from_candid_BedType_n31(_uploadFile, _downloadFile, value.bedType),
        hospitalId: value.hospitalId
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: _AppRole;
    name: string;
    hospitalId: [] | [_HospitalId];
}): {
    appRole: AppRole;
    name: string;
    hospitalId?: HospitalId;
} {
    return {
        appRole: from_candid_AppRole_n39(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        hospitalId: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.hospitalId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Aneg: null;
} | {
    Apos: null;
} | {
    Bneg: null;
} | {
    Bpos: null;
} | {
    Oneg: null;
} | {
    Opos: null;
} | {
    ABneg: null;
} | {
    ABpos: null;
}): BloodGroup {
    return "Aneg" in value ? BloodGroup.Aneg : "Apos" in value ? BloodGroup.Apos : "Bneg" in value ? BloodGroup.Bneg : "Bpos" in value ? BloodGroup.Bpos : "Oneg" in value ? BloodGroup.Oneg : "Opos" in value ? BloodGroup.Opos : "ABneg" in value ? BloodGroup.ABneg : "ABpos" in value ? BloodGroup.ABpos : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupied: null;
} | {
    available: null;
}): BedStatus {
    return "occupied" in value ? BedStatus.occupied : "available" in value ? BedStatus.available : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ICU: null;
} | {
    general: null;
}): BedType {
    return "ICU" in value ? BedType.ICU : "general" in value ? BedType.general : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    doctor: null;
} | {
    superAdmin: null;
} | {
    hospitalAdmin: null;
}): AppRole {
    return "patient" in value ? AppRole.patient : "doctor" in value ? AppRole.doctor : "superAdmin" in value ? AppRole.superAdmin : "hospitalAdmin" in value ? AppRole.hospitalAdmin : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BloodStock>): Array<BloodStock> {
    return value.map((x)=>from_candid_BloodStock_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medicine>): Array<Medicine> {
    return value.map((x)=>from_candid_Medicine_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bed>): Array<Bed> {
    return value.map((x)=>from_candid_Bed_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BloodGroup>): Array<BloodGroup> {
    return value.map((x)=>from_candid_BloodGroup_n20(_uploadFile, _downloadFile, x));
}
function to_candid_AppRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_BedStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BedStatus): _BedStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_BedType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BedType): _BedType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_BloodGroup_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): _BloodGroup {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierId | null): [] | [_SupplierId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: AppRole;
    name: string;
    hospitalId?: HospitalId;
}): {
    appRole: _AppRole;
    name: string;
    hospitalId: [] | [_HospitalId];
} {
    return {
        appRole: to_candid_AppRole_n15(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        hospitalId: value.hospitalId ? candid_some(value.hospitalId) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    patient: null;
} | {
    doctor: null;
} | {
    superAdmin: null;
} | {
    hospitalAdmin: null;
} {
    return value == AppRole.patient ? {
        patient: null
    } : value == AppRole.doctor ? {
        doctor: null
    } : value == AppRole.superAdmin ? {
        superAdmin: null
    } : value == AppRole.hospitalAdmin ? {
        hospitalAdmin: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BedStatus): {
    occupied: null;
} | {
    available: null;
} {
    return value == BedStatus.occupied ? {
        occupied: null
    } : value == BedStatus.available ? {
        available: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): {
    Aneg: null;
} | {
    Apos: null;
} | {
    Bneg: null;
} | {
    Bpos: null;
} | {
    Oneg: null;
} | {
    Opos: null;
} | {
    ABneg: null;
} | {
    ABpos: null;
} {
    return value == BloodGroup.Aneg ? {
        Aneg: null
    } : value == BloodGroup.Apos ? {
        Apos: null
    } : value == BloodGroup.Bneg ? {
        Bneg: null
    } : value == BloodGroup.Bpos ? {
        Bpos: null
    } : value == BloodGroup.Oneg ? {
        Oneg: null
    } : value == BloodGroup.Opos ? {
        Opos: null
    } : value == BloodGroup.ABneg ? {
        ABneg: null
    } : value == BloodGroup.ABpos ? {
        ABpos: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BedType): {
    ICU: null;
} | {
    general: null;
} {
    return value == BedType.ICU ? {
        ICU: null
    } : value == BedType.general ? {
        general: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
