/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const HospitalId = IDL.Text;
export const BedType = IDL.Variant({ 'ICU' : IDL.Null, 'general' : IDL.Null });
export const BedId = IDL.Nat;
export const Time = IDL.Int;
export const SupplierId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppRole = IDL.Variant({
  'patient' : IDL.Null,
  'doctor' : IDL.Null,
  'superAdmin' : IDL.Null,
  'hospitalAdmin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppRole,
  'name' : IDL.Text,
  'hospitalId' : IDL.Opt(HospitalId),
});
export const MedicineId = IDL.Nat;
export const BloodGroup = IDL.Variant({
  'Aneg' : IDL.Null,
  'Apos' : IDL.Null,
  'Bneg' : IDL.Null,
  'Bpos' : IDL.Null,
  'Oneg' : IDL.Null,
  'Opos' : IDL.Null,
  'ABneg' : IDL.Null,
  'ABpos' : IDL.Null,
});
export const BloodStock = IDL.Record({
  'hospitalId' : HospitalId,
  'bloodGroup' : BloodGroup,
  'quantity' : IDL.Nat,
  'minQuantity' : IDL.Nat,
});
export const Medicine = IDL.Record({
  'id' : MedicineId,
  'expiryDate' : Time,
  'name' : IDL.Text,
  'hospitalId' : HospitalId,
  'quantity' : IDL.Nat,
  'minQuantity' : IDL.Nat,
  'supplierId' : IDL.Opt(SupplierId),
});
export const Supplier = IDL.Record({
  'id' : SupplierId,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'hospitalId' : HospitalId,
});
export const BedStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'available' : IDL.Null,
});
export const Bed = IDL.Record({
  'id' : BedId,
  'status' : BedStatus,
  'bedType' : BedType,
  'hospitalId' : HospitalId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBed' : IDL.Func([HospitalId, BedType], [BedId], []),
  'addMedicine' : IDL.Func(
      [HospitalId, IDL.Text, IDL.Nat, IDL.Nat, Time, IDL.Opt(SupplierId)],
      [],
      [],
    ),
  'addSupplier' : IDL.Func([HospitalId, IDL.Text, IDL.Text], [SupplierId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'deleteMedicine' : IDL.Func([MedicineId], [], []),
  'getAllBloodStock' : IDL.Func([HospitalId], [IDL.Vec(BloodStock)], ['query']),
  'getAllMedicines' : IDL.Func([HospitalId], [IDL.Vec(Medicine)], ['query']),
  'getAllSuppliers' : IDL.Func([HospitalId], [IDL.Vec(Supplier)], ['query']),
  'getBed' : IDL.Func([BedId], [IDL.Opt(Bed)], ['query']),
  'getBedStats' : IDL.Func(
      [HospitalId],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'occupied' : IDL.Nat,
          'available' : IDL.Nat,
          'icuOccupied' : IDL.Nat,
          'icuAvailable' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getBedStatsLegacy' : IDL.Func(
      [HospitalId],
      [
        IDL.Record({
          'icuBeds' : IDL.Nat,
          'occupiedBeds' : IDL.Nat,
          'totalBeds' : IDL.Nat,
          'availableBeds' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getBedsByStatus' : IDL.Func(
      [HospitalId, BedStatus],
      [IDL.Vec(Bed)],
      ['query'],
    ),
  'getBedsByTypeAndStatus' : IDL.Func(
      [HospitalId, BedType, BedStatus],
      [IDL.Vec(Bed)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpiringMedicines' : IDL.Func(
      [HospitalId],
      [IDL.Vec(Medicine)],
      ['query'],
    ),
  'getLowStockBloodGroups' : IDL.Func(
      [HospitalId],
      [IDL.Vec(BloodGroup)],
      ['query'],
    ),
  'getLowStockMedicines' : IDL.Func(
      [HospitalId],
      [IDL.Vec(Medicine)],
      ['query'],
    ),
  'getMedicinesBySupplier' : IDL.Func(
      [SupplierId],
      [IDL.Vec(Medicine)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBedStatus' : IDL.Func([BedId, BedStatus], [], []),
  'updateBloodStock' : IDL.Func(
      [HospitalId, BloodGroup, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateMedicine' : IDL.Func(
      [
        MedicineId,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(Time),
        IDL.Opt(SupplierId),
      ],
      [],
      [],
    ),
  'updateSupplier' : IDL.Func([SupplierId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const HospitalId = IDL.Text;
  const BedType = IDL.Variant({ 'ICU' : IDL.Null, 'general' : IDL.Null });
  const BedId = IDL.Nat;
  const Time = IDL.Int;
  const SupplierId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppRole = IDL.Variant({
    'patient' : IDL.Null,
    'doctor' : IDL.Null,
    'superAdmin' : IDL.Null,
    'hospitalAdmin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppRole,
    'name' : IDL.Text,
    'hospitalId' : IDL.Opt(HospitalId),
  });
  const MedicineId = IDL.Nat;
  const BloodGroup = IDL.Variant({
    'Aneg' : IDL.Null,
    'Apos' : IDL.Null,
    'Bneg' : IDL.Null,
    'Bpos' : IDL.Null,
    'Oneg' : IDL.Null,
    'Opos' : IDL.Null,
    'ABneg' : IDL.Null,
    'ABpos' : IDL.Null,
  });
  const BloodStock = IDL.Record({
    'hospitalId' : HospitalId,
    'bloodGroup' : BloodGroup,
    'quantity' : IDL.Nat,
    'minQuantity' : IDL.Nat,
  });
  const Medicine = IDL.Record({
    'id' : MedicineId,
    'expiryDate' : Time,
    'name' : IDL.Text,
    'hospitalId' : HospitalId,
    'quantity' : IDL.Nat,
    'minQuantity' : IDL.Nat,
    'supplierId' : IDL.Opt(SupplierId),
  });
  const Supplier = IDL.Record({
    'id' : SupplierId,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'hospitalId' : HospitalId,
  });
  const BedStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'available' : IDL.Null,
  });
  const Bed = IDL.Record({
    'id' : BedId,
    'status' : BedStatus,
    'bedType' : BedType,
    'hospitalId' : HospitalId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBed' : IDL.Func([HospitalId, BedType], [BedId], []),
    'addMedicine' : IDL.Func(
        [HospitalId, IDL.Text, IDL.Nat, IDL.Nat, Time, IDL.Opt(SupplierId)],
        [],
        [],
      ),
    'addSupplier' : IDL.Func(
        [HospitalId, IDL.Text, IDL.Text],
        [SupplierId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'deleteMedicine' : IDL.Func([MedicineId], [], []),
    'getAllBloodStock' : IDL.Func(
        [HospitalId],
        [IDL.Vec(BloodStock)],
        ['query'],
      ),
    'getAllMedicines' : IDL.Func([HospitalId], [IDL.Vec(Medicine)], ['query']),
    'getAllSuppliers' : IDL.Func([HospitalId], [IDL.Vec(Supplier)], ['query']),
    'getBed' : IDL.Func([BedId], [IDL.Opt(Bed)], ['query']),
    'getBedStats' : IDL.Func(
        [HospitalId],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'occupied' : IDL.Nat,
            'available' : IDL.Nat,
            'icuOccupied' : IDL.Nat,
            'icuAvailable' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getBedStatsLegacy' : IDL.Func(
        [HospitalId],
        [
          IDL.Record({
            'icuBeds' : IDL.Nat,
            'occupiedBeds' : IDL.Nat,
            'totalBeds' : IDL.Nat,
            'availableBeds' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getBedsByStatus' : IDL.Func(
        [HospitalId, BedStatus],
        [IDL.Vec(Bed)],
        ['query'],
      ),
    'getBedsByTypeAndStatus' : IDL.Func(
        [HospitalId, BedType, BedStatus],
        [IDL.Vec(Bed)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpiringMedicines' : IDL.Func(
        [HospitalId],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getLowStockBloodGroups' : IDL.Func(
        [HospitalId],
        [IDL.Vec(BloodGroup)],
        ['query'],
      ),
    'getLowStockMedicines' : IDL.Func(
        [HospitalId],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getMedicinesBySupplier' : IDL.Func(
        [SupplierId],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBedStatus' : IDL.Func([BedId, BedStatus], [], []),
    'updateBloodStock' : IDL.Func(
        [HospitalId, BloodGroup, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateMedicine' : IDL.Func(
        [
          MedicineId,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(Time),
          IDL.Opt(SupplierId),
        ],
        [],
        [],
      ),
    'updateSupplier' : IDL.Func([SupplierId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };