/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'patient' : null } |
  { 'doctor' : null } |
  { 'superAdmin' : null } |
  { 'hospitalAdmin' : null };
export interface Bed {
  'id' : BedId,
  'status' : BedStatus,
  'bedType' : BedType,
  'hospitalId' : HospitalId,
}
export type BedId = bigint;
export type BedStatus = { 'occupied' : null } |
  { 'available' : null };
export type BedType = { 'ICU' : null } |
  { 'general' : null };
export type BloodGroup = { 'Aneg' : null } |
  { 'Apos' : null } |
  { 'Bneg' : null } |
  { 'Bpos' : null } |
  { 'Oneg' : null } |
  { 'Opos' : null } |
  { 'ABneg' : null } |
  { 'ABpos' : null };
export interface BloodStock {
  'hospitalId' : HospitalId,
  'bloodGroup' : BloodGroup,
  'quantity' : bigint,
  'minQuantity' : bigint,
}
export type HospitalId = string;
export interface Medicine {
  'id' : MedicineId,
  'expiryDate' : Time,
  'name' : string,
  'hospitalId' : HospitalId,
  'quantity' : bigint,
  'minQuantity' : bigint,
  'supplierId' : [] | [SupplierId],
}
export type MedicineId = bigint;
export interface Supplier {
  'id' : SupplierId,
  'contactInfo' : string,
  'name' : string,
  'hospitalId' : HospitalId,
}
export type SupplierId = bigint;
export type Time = bigint;
export interface UserProfile {
  'appRole' : AppRole,
  'name' : string,
  'hospitalId' : [] | [HospitalId],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBed' : ActorMethod<[HospitalId, BedType], BedId>,
  'addMedicine' : ActorMethod<
    [HospitalId, string, bigint, bigint, Time, [] | [SupplierId]],
    undefined
  >,
  'addSupplier' : ActorMethod<[HospitalId, string, string], SupplierId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
  'deleteMedicine' : ActorMethod<[MedicineId], undefined>,
  'getAllBloodStock' : ActorMethod<[HospitalId], Array<BloodStock>>,
  'getAllMedicines' : ActorMethod<[HospitalId], Array<Medicine>>,
  'getAllSuppliers' : ActorMethod<[HospitalId], Array<Supplier>>,
  'getBed' : ActorMethod<[BedId], [] | [Bed]>,
  'getBedStats' : ActorMethod<
    [HospitalId],
    {
      'total' : bigint,
      'occupied' : bigint,
      'available' : bigint,
      'icuOccupied' : bigint,
      'icuAvailable' : bigint,
    }
  >,
  'getBedStatsLegacy' : ActorMethod<
    [HospitalId],
    {
      'icuBeds' : bigint,
      'occupiedBeds' : bigint,
      'totalBeds' : bigint,
      'availableBeds' : bigint,
    }
  >,
  'getBedsByStatus' : ActorMethod<[HospitalId, BedStatus], Array<Bed>>,
  'getBedsByTypeAndStatus' : ActorMethod<
    [HospitalId, BedType, BedStatus],
    Array<Bed>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpiringMedicines' : ActorMethod<[HospitalId], Array<Medicine>>,
  'getLowStockBloodGroups' : ActorMethod<[HospitalId], Array<BloodGroup>>,
  'getLowStockMedicines' : ActorMethod<[HospitalId], Array<Medicine>>,
  'getMedicinesBySupplier' : ActorMethod<[SupplierId], Array<Medicine>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBedStatus' : ActorMethod<[BedId, BedStatus], undefined>,
  'updateBloodStock' : ActorMethod<
    [HospitalId, BloodGroup, bigint, bigint],
    undefined
  >,
  'updateMedicine' : ActorMethod<
    [MedicineId, [] | [bigint], [] | [bigint], [] | [Time], [] | [SupplierId]],
    undefined
  >,
  'updateSupplier' : ActorMethod<[SupplierId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];